### ISSUE TITLE
17/69 of dockerfile build returns syntax error

### ISSUE THREAD

**Issue by tyler-lynch** [conema/ZAGA#3]
When performing step 2 and running the dockerfile I get this error:

 `=> ERROR [17/69] RUN pip3 install --upgrade "google-auth-oauthlib[to  1.1s

 > [17/69] RUN pip3 install --upgrade "google-auth-oauthlib[tool]":
#20 0.955 Traceback (most recent call last):
#20 0.955   File "/usr/local/bin/pip3", line 7, in <module>
#20 0.955     from pip._internal.cli.main import main
#20 0.955   File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 57
#20 0.955     sys.stderr.write(f"ERROR: {exc}")
#20 0.955                                    ^
#20 0.955 SyntaxError: invalid syntax

executor failed running [/bin/sh -c pip3 install --upgrade "google-auth-oauthlib[tool]"]: exit code: 1

**Comment by conema** [comment]
Hi @tyler-lynch,
PIP has dropped support for Python 3.5.
You can try two things, I feel that the first one would be the easier:
- Change all the occurrencies of python 3.5 in the Dockerfile with a more recent version of python
- Install pip for python 3.5 by changing the Dockerfile (see here: https://stackoverflow.com/a/66213117 )

 I'm currently with my mobile phone, so I can't help you by writing precisely which rows need to be edited, let me know if you sort it out or if you need more help

PS: do a pull request if you resolve it
