### ISSUE TITLE
Running Choreographe ga.pml

### ISSUE THREAD

**Issue by anjalie-ch** [conema/ZAGA#4]
When performing "Step 8 Start GA"
I have opened the ga.pml on choreographe and when running the behavior I get this error in the log:

[ERROR] behavior.box :__init__:10 _Behavior__lastUploadedChoregrapheBehaviorbehavior_12764739968:/GA_7/Speech Reco._5: 	ALProxy::ALProxy 	Can't find service: ALSpeechRecognition 
[ERROR] behavior.box :__init__:8 _Behavior__lastUploadedChoregrapheBehaviorbehavior_12764739968:/OD_3/Speech Reco._5: 	ALProxy::ALProxy 	Can't find service: ALSpeechRecognition 
[ERROR] behavior.box :__init__:10 _Behavior__lastUploadedChoregrapheBehaviorbehavior_12764739968:/OD_3/Speech Reco. (1)_18: 	ALProxy::ALProxy 	Can't find service: ALSpeechRecognition 
[ERROR] behavior.box :__init__:10 _Behavior__lastUploadedChoregrapheBehaviorbehavior_12764739968:/OD_3/Speech Reco. (2)_31: 	ALProxy::ALProxy 	Can't find service: ALSpeechRecognition 
[ERROR] behavior.box :__init__:10 _Behavior__lastUploadedChoregrapheBehaviorbehavior_12764739968:/OD_3/Speech Reco. (3)_55: 	ALProxy::ALProxy 	Can't find service: ALSpeechRecognition 
[ERROR] behavior.box :FMBox::createPythonModule:0 _Behavior__lastUploadedChoregrapheBehaviorbehavior_12764739968:/AC_4/Leg L Up_67: Box creation failed with the error: <type 'exceptions.ImportError'> No module named almath

**Comment by conema** [comment]
Hi @anjalie-ch,
did you try to install the almath package [0] via pip?

[0] https://pypi.org/project/almath/

**Comment by anjalie-ch** [comment]
I realized it was because I had been connected to the virtual robot rather than the actual nao...
